# Generated by Django 3.1.1 on 2020-09-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productImage',
        ),
    ]
