# Generated by Django 3.1.1 on 2020-09-24 05:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='score',
            field=models.IntegerField(default=datetime.datetime(2020, 9, 24, 5, 42, 54, 857954, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
        ),
    ]
