# Generated by Django 3.1.1 on 2020-09-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20200924_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='score',
        ),
    ]
