# Generated by Django 3.1.1 on 2020-09-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_remove_productreview_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
